### ISSUE TITLE
Got unknown OP_MSG command: getlasterror

### ISSUE THREAD

**Issue by whisper-bye** [fcoury/oxide#66]
./oxide  --postgres-url "postgres://postgres:postgres@localhost:5432/test"
[2022-08-27T17:28:22Z INFO  oxide::server] Connecting to postgres://*****:*****@localhost:5432/test...
[2022-08-27T17:28:22Z INFO  oxide::server] OxideDB listening on 0.0.0.0:27017...
[2022-08-27T17:28:24Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:24Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:27Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:42Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:42Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:42Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAccessError: field is not present', src/commands/insert.rs:20:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-08-27T17:28:46Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:46Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:46Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:28:54Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]
[2022-08-27T17:29:46Z ERROR oxide::handler] Got unknown OP_MSG command: getlasterror
    [Document({"getlasterror": Int32(1), "$db": String("admin")})]

**Comment by fcoury** [comment]
Hi there @whisper-bye thanks so much for reporting this error. However, I can't understand what's going on if you don't provide me with the commands you were trying to run. 

Could you please add those to the issue? Thanks!

**Comment by fcoury** [comment]
Just to add to what I said before. Not having the getlasterror command is not what's breaking your app, it can run fine without this command, the real problem is here:

```
thread '' panicked at 'called Result::unwrap() on an Err value: ValueAccessError: field is not present', src/commands/insert.rs:20:66
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

It seems like the app or command you're running is lacking a `document` attribute (or Oxide is failing to get it), so this is what I am trying to get before investigating the issue. 

Hopefully it makes sense.

**Comment by whisper-bye** [comment]
just insert
```
db.inventory.insertOne(
   { item: "canvas", qty: 100, tags: ["cotton"], size: { h: 28, w: 35.5, uom: "cm" } }
)
```

**Comment by fcoury** [comment]
Just tested and it worked fine here:

```
test> db.inventory.insertOne(
...    { item: "canvas", qty: 100, tags: ["cotton"], size: { h: 28, w: 35.5, uom: "cm" } }
... )
{
  acknowledged: true,
  insertedId: ObjectId("630b608fd9f714ef43e7c364")
}
```

And Oxide logs:

```
[2022-08-28T12:33:19Z DEBUG oxide::handler] OP_MSG command: insert
[2022-08-28T12:33:19Z DEBUG oxide::pg] SQL: INSERT INTO "test"."inventory" VALUES ($1) - [
        Object({
            "item": String(
                "canvas",
            ),
            "qty": Number(
                100,
            ),
            "tags": Array([
                String(
                    "cotton",
                ),
            ]),
            "size": Object({
                "h": Number(
                    28,
                ),
                "w": Object({
                    "$f": Number(
                        35.5,
                    ),
                }),
                "uom": String(
                    "cm",
                ),
            }),
            "_id": Object({
                "$o": String(
                    "630b608fd9f714ef43e7c364",
                ),
            }),
        }),
    ]
```

Can you check which version you're running with `./oxide --version` please?

**Comment by whisper-bye** [comment]
./oxide --version
oxide 0.1.5

jetbrains idea console

2021 Macbook Pro M1 Pro

**Comment by fcoury** [comment]
Sorry this is taking too long to debug, still can't replicate it. Can you try running oxide with the debug flag on please?

```
./oxide --debug
```

Thanks so much for your help, I did my test using mongosh and not Jetbrains Idea (since I don't have it). They might be using a different protocol to send the message.

**Comment by fcoury** [comment]
Meanwhile I am downloading IDEA to try it, if I can replicate I'll let you know here.

**Comment by fcoury** [comment]
Alright, just replicated the issue here! It only happens (so far) on the database console. 

I will let you know once I figure out next steps to fix it.

Thank you so much again for taking the time.

**Comment by fcoury** [comment]
For documentation purposes here's what Oxide "sees" with the current implementation:

```
[2022-08-28T17:10:53Z DEBUG oxide::handler] OP_MSG command: insert
[2022-08-28T17:10:53Z DEBUG oxide::commands::insert] insert doc = Document({
        "insert": String(
            "inventory",
        ),
        "ordered": Boolean(
            true,
        ),
        "$db": String(
            "test",
        ),
    })
```

The document doesn't have the expected format, which might be related to how we're paring the wire protocol.

**Comment by fcoury** [comment]
Took me a bit of time but finally made it work:

![image](https://user-images.githubusercontent.com/1371/187097642-6f63a0e1-8da3-4301-a3b9-138560c308a5.png)

Please let me know if you find any other weird behaviors with your client and thank you yet again!
